2022-12-06 12:28:46,394 INFO    Thread-9  :2526828 [wandb_setup.py:_flush():68] Configure stats pid to 2526828
2022-12-06 12:28:46,394 INFO    Thread-9  :2526828 [wandb_setup.py:_flush():68] Loading settings from /home/sin/.config/wandb/settings
2022-12-06 12:28:46,394 INFO    Thread-9  :2526828 [wandb_setup.py:_flush():68] Loading settings from /home/sin/PycharmProjects/tutorial/wandb/settings
2022-12-06 12:28:46,394 INFO    Thread-9  :2526828 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True', 'entity': 'sb2539', 'project': 'dbscan_demo_outlier', 'root_dir': '/home/sin/PycharmProjects/tutorial', 'run_id': 'erxit9qq', 'sweep_param_path': '/home/sin/PycharmProjects/tutorial/wandb/sweep-85x6fw31/config-erxit9qq.yaml', 'sweep_id': '85x6fw31'}
2022-12-06 12:28:46,394 INFO    Thread-9  :2526828 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'dbscan.py', 'program': '/home/sin/PycharmProjects/tutorial/dbscan.py'}
2022-12-06 12:28:46,395 INFO    Thread-9  :2526828 [wandb_init.py:_log_setup():476] Logging user logs to /home/sin/PycharmProjects/tutorial/wandb/run-20221206_122846-erxit9qq/logs/debug.log
2022-12-06 12:28:46,395 INFO    Thread-9  :2526828 [wandb_init.py:_log_setup():477] Logging internal logs to /home/sin/PycharmProjects/tutorial/wandb/run-20221206_122846-erxit9qq/logs/debug-internal.log
2022-12-06 12:28:46,395 INFO    Thread-9  :2526828 [wandb_init.py:init():516] calling init triggers
2022-12-06 12:28:46,395 INFO    Thread-9  :2526828 [wandb_init.py:init():520] wandb.init called with sweep_config: {'eps': 0.05, 'min_sample': [6, 7, 8, 9, 10]}
config: {}
2022-12-06 12:28:46,395 INFO    Thread-9  :2526828 [wandb_init.py:init():569] starting backend
2022-12-06 12:28:46,396 INFO    Thread-9  :2526828 [wandb_init.py:init():573] setting up manager
2022-12-06 12:28:46,402 INFO    Thread-9  :2526828 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-12-06 12:28:46,407 INFO    Thread-9  :2526828 [wandb_init.py:init():580] backend started and connected
2022-12-06 12:28:46,413 INFO    Thread-9  :2526828 [wandb_run.py:_config_callback():1160] config_cb None None {'eps': 0.05, 'min_sample': [6, 7, 8, 9, 10]}
2022-12-06 12:28:46,416 INFO    Thread-9  :2526828 [wandb_init.py:init():658] updated telemetry
2022-12-06 12:28:46,416 INFO    Thread-9  :2526828 [wandb_init.py:init():694] communicating run to backend with 60 second timeout
2022-12-06 12:28:46,997 INFO    Thread-9  :2526828 [wandb_run.py:_on_init():2000] communicating current version
2022-12-06 12:28:47,109 INFO    Thread-9  :2526828 [wandb_run.py:_on_init():2004] got version response 
2022-12-06 12:28:47,110 INFO    Thread-9  :2526828 [wandb_init.py:init():728] starting run threads in backend
2022-12-06 12:28:50,308 INFO    Thread-9  :2526828 [wandb_run.py:_console_start():1980] atexit reg
2022-12-06 12:28:50,309 INFO    Thread-9  :2526828 [wandb_run.py:_redirect():1838] redirect: SettingsConsole.WRAP_RAW
2022-12-06 12:28:50,309 INFO    Thread-9  :2526828 [wandb_run.py:_redirect():1903] Wrapping output streams.
2022-12-06 12:28:50,309 INFO    Thread-9  :2526828 [wandb_run.py:_redirect():1925] Redirects installed.
2022-12-06 12:28:50,310 INFO    Thread-9  :2526828 [wandb_init.py:init():765] run started, returning control to user process
2022-12-06 12:28:50,327 INFO    Thread-9  :2526828 [wandb_run.py:_finish():1746] finishing run sb2539/dbscan_demo_outlier/erxit9qq
2022-12-06 12:28:50,327 INFO    Thread-9  :2526828 [wandb_run.py:_atexit_cleanup():1949] got exitcode: 1
2022-12-06 12:28:50,327 INFO    Thread-9  :2526828 [wandb_run.py:_restore():1932] restore
2022-12-06 12:28:50,327 INFO    Thread-9  :2526828 [wandb_run.py:_restore():1938] restore done
2022-12-06 12:28:53,329 INFO    Thread-9  :2526828 [wandb_run.py:_restore():1932] restore
2022-12-06 12:28:53,329 INFO    Thread-9  :2526828 [wandb_run.py:_restore():1938] restore done
2022-12-06 12:28:54,333 ERROR   Thread-9  :2526828 [wandb_run.py:_atexit_cleanup():1970] Problem finishing run
Traceback (most recent call last):
  File "/home/sin/anaconda3/envs/semi/lib/python3.7/site-packages/wandb/agents/pyagent.py", line 298, in _run_job
    self._function()
  File "/home/sin/PycharmProjects/tutorial/dbscan.py", line 105, in run_sweep
    dbscan = DBSCAN(eps=w_config.eps, min_samples=w_config.min_sample).fit(df)
  File "/home/sin/anaconda3/envs/semi/lib/python3.7/site-packages/sklearn/cluster/_dbscan.py", line 388, in fit
    core_samples = np.asarray(n_neighbors >= self.min_samples, dtype=np.uint8)
ValueError: operands could not be broadcast together with shapes (2156,) (5,) 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sin/anaconda3/envs/semi/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1958, in _atexit_cleanup
    self._on_finish()
  File "/home/sin/anaconda3/envs/semi/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 2266, in _on_finish
    _ = exit_handle.wait(timeout=-1, on_progress=self._on_progress_exit)
  File "/home/sin/anaconda3/envs/semi/lib/python3.7/site-packages/wandb/sdk/lib/mailbox.py", line 261, in wait
    found = self._slot._get_and_clear(timeout=wait_timeout)
  File "/home/sin/anaconda3/envs/semi/lib/python3.7/site-packages/wandb/sdk/lib/mailbox.py", line 118, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/home/sin/anaconda3/envs/semi/lib/python3.7/site-packages/wandb/sdk/lib/mailbox.py", line 114, in _wait
    return self._event.wait(timeout=timeout)
  File "/home/sin/anaconda3/envs/semi/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/home/sin/anaconda3/envs/semi/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
Exception
